---
title: "Saudi Used Cars EDA"
format:
  html:
    code-fold: true
    code-copy: true
    toc: true
    toc-location: left
    smooth-scroll: true
    number-depth: 3

kernel: python3
---
# <font color='lightsteelblue'> Data </font>
 

##### <font color='black'>The dataset contains the following variables:
</font>

| Variable Name                                                                     |   Unique Values |
|:----------------------------------------------------------------------------------|:---------------:|
| Make : Name of the car company                                                    |              57 |
| Type : Name of a car product                                                      |             349 |
| Year : Year of Manufacturing                                                      |              46 |
| Origin : Country of importer (Gulf / Saudi / Other)                               |               3 |
| Color : Color of the used car                                                     |              15 |
| Options : Full Options / Semi-Full / Standard                                     |               3 |
| Engine_Size : The engine size of used car                                         |              69 |
| Fuel_Type : Fuel type size of used car (Diesel / Gas / Hybrid)                    |               3 |
| Gear_Type : Automatic / Manual                                                    |               2 |
| Mileage : The average distance that a vehicle can travel on (in km)               |            1694 |
| Region : The region in which the used car was offered for sale                    |              27 |
| Price : Price of the used car (in SAR)                                            |             451 |
| Negotiable : If True, the price is 0. This means the price is negotiable (not set)|               1 |

##### <font color='black'>Import the libraries & Data</font>
```{python}
from tabulate import tabulate
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
import numpy as np 
import matplotlib as mpl

sauc = pd.read_csv('../data/UsedCarsSA_Clean_EN.csv') 
```



## <font color='lightsteelblue'> Data Preprocessing </font>

A look for the dataset

```{python}
display(sauc.head())
print("\n")
```

##### <br> <font color='black'> Data informations </font>

```{python}

display(sauc.info())
print("\n")

```

##### <font color='black'>Data Describtion for catagorical variables before processing</font> 

```{python}
display(sauc.describe(include = 'object'))
print("\n")


```

##### <font color='black'>Data Describtion for numerical variables before processing</font>

```{python}

display(sauc.describe())
print("\n")

```

##### <font color='black'>Checking the null values</font>

```{python}
display(sauc.isna().sum())
print("\n")

```

##### <font color='black'>Check the duplicated rows and delete them</font>

```{python}
duplicateOFRow = sauc[sauc.duplicated()] # check 
print('These are the duplicated rows :  \n')
display(duplicateOFRow) 
sauc = sauc.drop_duplicates() 
print("\n")

```

##### <font color='black'>Dropping the rows having price equal to zero</font>

```{python}

# Dropping the rows having price equal to zero
sauc = sauc[sauc['Price'] != 0]
print('The data shape after the drop of the zeros', sauc.shape)
print("\n")

```

##### <font color='black'>It is obvious that some of the values look too high to be taken into account when determining a car's pricing. We made the decision to remove the rows with prices less than 7000 Riyals in order to avoid skewing the results.</font>

```{python}
#Dropping the rows having price equal to zero
sauc = sauc[sauc['Price'] > 7000]
print('The data shape after the drop', sauc.shape)
print("\n")

```

##### <font color='black'>Replace the Unknown value in the origin column by the mode</font>

```{python}
# replace the unknown value in the column by the mode 
print('The current number of uniqe values is : 4')
sauc['Origin'] = sauc['Origin'].apply( lambda x : x.replace('Unknown', 'Saudi') )  
sauc['Origin'].nunique() 
print('The number of uniqe values After the change is : ' , sauc['Origin'].nunique() )
print('The data shape after the cleaning', sauc.shape)
print("\n")

```

##### <font color='black'>Data Describtion for catagorical variables after processing</font> 

```{python}
display(sauc.describe(include = 'object'))
print("\n")


```

##### <font color='black'>Data Describtion for numerical variables after processing</font>

```{python}

display(sauc.describe())
print("\n")

```

# <font color='lightsteelblue'> EDA </font>

**<font color = 'black'><font size="5">We will start with exploring some general informations about the data and proceeds with more in depth analysis to know which type of cars has the highest resale values</font>**

## What Is The Resold Cars Price?

```{python}
plt.figure(figsize=(10,5))
np.random.seed(6789)
x = sauc['Price']
result = plt.hist(x, bins=150, color='c', edgecolor='k', alpha=0.65)
plt.axvline(x.median(), color='k', linestyle='dashed', linewidth=1)
min_ylim, max_ylim = plt.ylim()
plt.text(x.median()*1.1, max_ylim*0.9, 'Median: {:.2f}'.format(x.median()))
plt.title('Resold Cars Price', fontsize=20)
plt.xlabel('Price (Million SAR)')
plt.ylabel('Count of Cars');
```

**Insights:**

Price was positively skewed that's why we showed the median.

## What is The Most Famous Car Companies? 

```{python}
# Visualizing the different car company names available
plt.style.use('ggplot')
%config InlineBackend.figure_format = 'retina'
%matplotlib inline
plt.rcParams['figure.figsize'] = [20,8]
ax = sauc['Make'].value_counts().plot(kind='bar', colormap = 'BrBG')
ax.title.set_text('Numbers of Resold Cars by Brand')
plt.xlabel("Company")
plt.ylabel("Count of Cars");
```

**Insights:** 


Toyota, Hyundai, and Ford are among the most resold cars.

## How does the price differ in each company and model year?

```{python}
y = sauc['Price']
x = sauc['Make']
colors = sauc['Year']
plt.figure(figsize=(20, 5))
plt.scatter(x,y, s=10, c=colors, alpha=0.7)
plt.colorbar(orientation="vertical", label="Year")
plt.title('Price in Each Company and Model Year', fontsize=20)
plt.xlabel('Company Name')
plt.ylabel('Price (Million SAR)')
plt.xticks(rotation=90);

```

**Insights:**

This plot shows the price according to each company & year, Marcedes has the heighest price followed by Bentley & Rolls-Royce.
not surprisingly, most price increase as the car's year increase (The newer the car, the heigher the price).

## What is most listed car model 

```{python}
d = dict(sauc['Type'].value_counts().iloc[:20]) 
keysList = list(d.keys())
ndf = pd.DataFrame(sauc[sauc['Type'].isin(keysList)].groupby(['Type'])['Price'].mean().sort_values(ascending = False))
plt.figure(figsize=(20,5))
plt.title('Car Model')
plt.xticks(rotation=80)
plt.xlabel('Car Model')
sns.countplot(x = 'Type' ,data = sauc[sauc['Type'].isin(keysList)])
plt.show();
```

**Insights:** 

The plot shows the top 20 cars. We have Accent and Land Cruiser and Camry on the top  

## What is the Avarage Price per Car Model?

```{python}
d = dict(sauc['Type'].value_counts().iloc[:20]) 
keysList = list(d.keys())
ndf = pd.DataFrame(sauc[sauc['Type'].isin(keysList)].groupby(['Type'])['Price'].mean().sort_values(ascending = False))
plt.figure(figsize=(20,5))
ndf.plot.bar(colormap = 'PuOr' )
plt.title('Cars Model Average Price')
plt.xticks(rotation=80)
plt.xlabel('Car Model')
plt.ylabel('Average Price');
plt.ticklabel_format(useOffset=False, style='plain', axis='y')
plt.show();
```

**Insights:** 

Among the top 20 listed cars. Range Rover has the highest average price. If we looked at the most listed cars which are Accent and Land Cruiser and Camry. Accent has the second lowest average price close to Camry whereas the Land is in the third place 

## Which Regin have the Highest Mileage and Lowest Mileage?

```{python}
plt.rcParams["figure.figsize"] = (20,10)
saucpr = pd.DataFrame(sauc.groupby(['Region'])['Price'].mean().sort_values(ascending = False))
saucpr.plot.bar(colormap = 'PuOr')
plt.title('Average Price per Region')
plt.ylabel("Average Price");
```

**Insights:**


Dammam, Riyadh, and Jeddah are cities where the most cars are sold.

##  What Is The Most Popular Cars Color?

```{python}

plt.figure(figsize=(10,5))
sauc.Color.value_counts().plot(kind='bar', rot=90, color='#004962')
plt.title('Colors Frequency', fontsize=20)
plt.xlabel('Color')
plt.ylabel('Count of Cars');
```

**Insights:**

White, black & silver are the most common colors whereas green, orange & yellow are the least frequent.

## Which Cars Options Are Most Popular ?

```{python}
plt.style.use('ggplot')
%config InlineBackend.figure_format = 'retina'
%matplotlib inline
fig = plt.figure(figsize=(10,5))
sauc.Options.value_counts().plot(kind='bar', rot=90)
plt.title('Cars Options (Full, Semi Full, Standard)', fontsize=20)
plt.xlabel('Options')
plt.ylabel('Cars');

```

**Insights:**

The full option cars has the highest number of cars

## Does the car option affect the Price?

```{python}
plt.style.use('ggplot')
%config InlineBackend.figure_format = 'retina'

f, ax = plt.subplots(figsize=(7, 5))
sns.despine(f)

sns.histplot(
    sauc,
    x="Price", hue="Options",
    multiple="stack",
    palette="light:m_r",
    edgecolor=".3",
    linewidth=.5,
    log_scale=True,
)
ax.xaxis.set_major_formatter(mpl.ticker.ScalarFormatter())
ax.set_xticks([10000, 25000, 100000, 500000]);

```

**Insights:**

- Semi full option cars are the least sold cars, while most of the sold cars are full option, in general.
- As the price increases, the sold cars are more likely to be full option.

## Show the density distribution for the price based on the car origin

```{python}
plt.figure(figsize=(15,5))
plt.subplot(1,2,1)
plt.title('Origin Histogram')
sns.countplot(x = 'Origin' , data = sauc)

plt.subplot(1,2,2)
plt.title('Origin vs Price')
sns.violinplot(x = 'Origin' , y = 'Price',data = sauc)

plt.ticklabel_format(useOffset=False, style='plain', axis='y')
plt.show()
```

**Insights:**

the plot show that the saudi cars price have a high density between 0-200K. The gulf cars have highest average

## What is the average price for each available engine ? 

```{python}
plt.style.use('ggplot')
scaucpr = pd.DataFrame(sauc.groupby(['Engine_Size'])['Price'].mean().sort_values(ascending = False)).add_suffix('_Average').reset_index()
plt.figure(figsize=(20,5))
sns.scatterplot(x= 'Engine_Size',  y = 'Price_Average' , data = scaucpr)
plt.title('Engine Size Average Price')
plt.xlabel('Engine Size')
plt.ylabel('Average Price');
plt.ticklabel_format(useOffset=False, style='plain', axis='y')
plt.show();
```

**Insights:**

Engine with a capacity between 6-7 have the highset average price 

## Does the engine class (Small if the engine < 5 else Large) proportion change in the new model cars?

```{python}
# make a new column that classifies the engine size
sauc['Engine_class'] = sauc['Engine_Size'].apply(lambda x : 'Small' if x < 5 else 'Large') 
ax = sns.histplot(x = 'Year' , hue = 'Engine_class', data = sauc[sauc["Year"] > 1990 ]) 
ax.set(xlabel='Cars model year', ylabel='Number of cars') 
plt.title('Cars Classication', fontsize=20);

```

**Insights:**

The cars listed in the website with a model from 2014 onward are domianted by small cars whereas the older cars 
have almost an equal  propotion

## What is the Price Behavior for Used Cars in Both the Fuel & Gear? 

```{python}
plt.figure(figsize=(15,5))
plt.subplot(1,2,1)
plt.title('Fuel Histogram')
sns.countplot(x = 'Fuel_Type' , data = sauc)

plt.subplot(1,2,2)
plt.title('Fuel_Type vs Price')
sns.boxplot(x = 'Fuel_Type' , y = 'Price',data = sauc)

plt.ticklabel_format(useOffset=False, style='plain', axis='y')
plt.show()

```

**Insights:** 

98% of the listed cars are Gas cars. There is only 10 Hybrid cars but they have the highest median price and thier price range is higher 

## How does the fuel type change overtime? (Toyota as an example)

```{python}
cars_t = sauc.loc[(sauc['Make'] == 'Toyota') & (sauc['Year'] > 1999)]
sns.set_theme(style="darkgrid")

# Plot the responses for different events and regions
sns.lineplot(x="Year", y="Price",
             hue="Fuel_Type", 
             data=cars_t);

```

**Insights:**

- As an example, we took the sample of Toyota cars (as Toyota has the higher frequency) from 2000 onward. We see that Diesel used cars had lower prices in 2005, but with the time it got higher than Gas used cars. Moreover, note the behavior of the Hybrid used cars.

## Correlation  matrix to show which variable affect the price for the overall dataset 

```{python}
# first a general corr then a corr based on every car cmopany 
#
cmap = sns.diverging_palette(230, 20, as_cmap=True)
#
# Draw the heatmap
#
sns.heatmap(sauc.corr(), annot=True, cmap=cmap);
```

**Insights:**

The engine size and the model year have a similar positive effect and the model year has the highest effect
on the price for the overall dataset

### More analysis to see what is the variable that affect the price for the top car makers?

```{python}
# First we take the unique values in 'Make' and the count for them. 
# The following code will creat a list for the maker names and for the count and make it a dict
maker_name, cars_counts = np.unique(sauc['Make'],return_counts=True)
d = dict(zip(maker_name,cars_counts))
top = {}
# Creat a new dict where we only have the top 12 cars makers as they represent 85% of the dataset 
for key, value in sorted(d.items(), key=lambda item: item[1], reverse= True)[:12]:
    top[key] = value  
nCols=3   # The number of columns that you want
nRows=4   # The number of correspomding rows 

fig,axes = plt.subplots(nRows, nCols, figsize=(25,25))
for ind,v in enumerate(top.keys()):
    cmap = sns.diverging_palette(230, 20, as_cmap=True)
    ax = sns.heatmap(sauc[sauc["Make"]== v ].corr(), annot=True, cmap=cmap,ax=axes.flatten()[ind])
    ax.title.set_text(v) 

plt.show() 
```

**Insights:**

The top 12 cars makers represent 85% from the dataset. The correlation shows that for 9 companies they follow tha same trend as the the overall dataset. In Toyota and Nissan, the engine size has the highest positive effect with the price, on the other hand, Honda engine size has a negative effect on the price.
 

# <font color='lightsteelblue'> Conclusion </font>

#### Toyota is the most famous company and Aston Martin is the least famous.

#### Dammam has the highest average price compared with other cities.

#### White is the most popular car color unlike yellow color

#### The median price for the cars is 59000 SAR

#### The price increase as the model year increase, and the cars are more likely to be a full option.

#### The prices of Toyota cars with Diesel fuel increased overtime.

#### For the overall dataset, the model year has the highest effect on the price but for Toyota, Nissan it is the engine size


